kind: Secret
apiVersion: v1
metadata:
  name: gateway-credential
data:
  tls.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN2ekNDQWFjQ0FRQXdEUVlKS29aSWh2Y05BUUVMQlFBd0h6RVBNQTBHQTFVRUNnd0dWbUYwWldOb01Rd3cKQ2dZRFZRUUREQU5OUVVNd0hoY05NakV3TnpBM01EZzFOekExV2hjTk1qSXdOekEzTURnMU56QTFXakFzTVJrdwpGd1lEVlFRRERCQm9ZWEoxWW1GdVpDNXJPSE11WTI5dE1ROHdEUVlEVlFRS0RBWldZWFJsWTJnd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEbllUcE1kb0pnWm1mV1phV0pMbndqOGgwekFYbHoKdXBUZE5PNi9VUi9aSENkOE0vVHhhNVFBU3laNFJNYUtUbExiWnNmR1pld25qVGdIREROb085NituS2xjOXlpQwo5cWo0dmp6dE1yNVdHZmZyMlZwZTlVOHloSWlJM3p2NVI3aHJueHdJb3k0M1VNSkVYUzZud1ZIOUE5amxPb2VMCjlDeFM5alRFS3RwSTMzeWxwUDk2M3FSbTJyWlVPTlZaOXdER0tkTXp4N0wxcityT29lVFFLOWgvZFprdmRISDQKOG8xUm1EeE5PK3pwakF3SitIbk1TVHBYa1ByNWVzLzF5dW9ESlJwbGEwZWc0SnZQeEZuNjFUQnpSVjBrMjBITApmVjJmOUc2ejFUU3BmSC9Ic05TdEF5Y0hzZ2loYnpRNVBWTFNmZitWNFJzV2FlMVpTVUYwVk91NUFnTUJBQUV3CkRRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDR3VrVXlzZ2tvVWlNNTNmSmhLMnN1NzFWeWNYazVmcWtzdENDZWUKdFRJMkRkUlIxb0ljSkI4WWd6N1dFOEMyWTZlUjJsTVhwYWpyTTZDR0J1dGpNZGZtdFBCcFA2NlJqT1lWZzZyKwpHMzBuNHJlemlkb25ha3FTY0I0RVNJVTJyamIwZnIySkVlMitjMkNpcUhFRWk4NFlHb3hiR0NUd0pPQmMzb0l5CkdPbHZlUDR3VmsyMi92alBBRUpCemFFMjNUMjBjT2lsUThSUmhEejk5VTlrYStTZHF6cmlYeG1Ybm1QZU9ZTVoKdnhqUHlzMWJhY0VNeUFPMnpKcGtkLzQ3b1FXbXNkckFTMmdpSVBTeFhUQU9nUktzK05vZUh2NFpUYk1xblNUYQp5TnNFTDZHYXpjUWJZMFNDY1pNNHhDQlRHYUxDZ0lsQnVIMnlUOEdRaEVlUWxYND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: >-
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRG5ZVHBNZG9KZ1ptZlcKWmFXSkxud2o4aDB6QVhsenVwVGROTzYvVVIvWkhDZDhNL1R4YTVRQVN5WjRSTWFLVGxMYlpzZkdaZXdualRnSApERE5vTzk2K25LbGM5eWlDOXFqNHZqenRNcjVXR2ZmcjJWcGU5VTh5aElpSTN6djVSN2hybnh3SW95NDNVTUpFClhTNm53Vkg5QTlqbE9vZUw5Q3hTOWpURUt0cEkzM3lscFA5NjNxUm0yclpVT05WWjl3REdLZE16eDdMMXIrck8Kb2VUUUs5aC9kWmt2ZEhINDhvMVJtRHhOTyt6cGpBd0orSG5NU1RwWGtQcjVlcy8xeXVvREpScGxhMGVnNEp2UAp4Rm42MVRCelJWMGsyMEhMZlYyZjlHNnoxVFNwZkgvSHNOU3RBeWNIc2dpaGJ6UTVQVkxTZmYrVjRSc1dhZTFaClNVRjBWT3U1QWdNQkFBRUNnZ0VBWllmZW95cmxyeE9Bd1MyOVkrTUlDbVgxdGlvUmQxMEtjYjhHZk9GR1RtankKVXFnaDljWTFIYVBjYjY0T1NTWnhhV0ZDakthdzUvSXFBYjJ5MlN4Y1k5d3UzV0ovWG1pS1lReHBnOVJlZlQzTAo4cXhmNFlkWGgxMXM1RkxBNkhRMlV0Tnc0OEZuU0ZLaHpJbnZMU0hCcm5yL3RDYm96OXNIa0NnRm80Y0NYak1OCnByZ24wbTdEcmgweTRXVWwyUXZqSzZsenNnbU45azUvWnAxMmxxbTFsVzMvbUwwWjJsMTEzb3hWejVLMlJibnEKRmJKMWxsQzBVLzZ1R2YzcFBkTDhrTXhjcXF5dSs2ZjkxQjJSanJiZXhTdllWUmFRcEpBbFNzclBHcDJBc1FjNwp3Tm9sSlRhQW1rWVFSRkEwT21RbXlYMUlibEUra2RxNmQxMTBwb3dLbVFLQmdRRDlJWHVQQWd2bFd5eEhDUDdxCjI4RWc4cW8vMkhFLzMvRXRDNHdueTFrRnlMWjFnSmwrTjVxYm9tMFdxVWxlWXFmcGxXb3NMVGlPVjBhd2VSZTQKZzM4TTRRWHl2SzY0MmlKZE1DdTRPQ0NjVmluMnhYdmZJNllabzB0YlltVWRqNmlPMk1IeDNTck5SRnBpL0R2Lwp1Z3d6am0vZ2lTWk00NWRvNlJwbEFFRThLd0tCZ1FEcUFLRXFLT1dpa2RNakg4anNJUlRZc04xUmFwRUtxcy9NCndyMHIvUXBuZU1hSlh4YWJkQlRXOWZSVGZHSUhBRDFpN1JVVmVyQ0NGYndYZUZKbUJFajFWSnJYbjBEQTZKMXYKMlkyQjZEdGJnK1o5Mk8yMS9DSnp1bTM4V3o0SVJBRnd4LzlORWdISUZmL01iN0lSMkhCTUVERTJrbkJPaEtNRApuQWpMN25peHF3S0JnUUNjRm5WMmJiQ2dNV1JRT1QvWDJzSndhcktJeEJLeGJJbnZXTnVIL21CYXJMVzJKeUovCkxoSnNQZkErdFF6RTR0amZ0SDdQMXVLMUF5UlgxWlBHOTI3MHBoMWczUEJ3bERIMGZLdTQ0UU5hNDlia2tFb2UKQW9GOTlhK1dIa3B6dkE0WVo1alFaNnpvL21rdCtKT1cwVWFNMUJ3d3ZPR2RNQXBCYXR3WHc5eDJHUUtCZ0dCUQp1QVZoWmZ0L0tEZVoycHFPbDBVRnIyTFdpVEtwMGZSRzU1UldoOVRGR25ycWY2U21wL2srclQwN3dpRjlrTWJLCkxOWjFkSGRtdU0rMFA3NHIzMWZUWmhTQVFTZmwxdjkxdlZBT0pYaHFseEdQbTNBL2duSzk5bzFiaFBIa0ErL0cKOGlkbjFRSGxSQytDZmZub2EzaHpaYjQva2loUFljV1hrT3RYa2FnWEFvR0FHUGxNaS9mSkswTm05NjdTYkJHQQpHcUVUMEJjeGNSTUxWQzRMRFo4MmRFTmlwaHpkdHdoT1Fmd0cyVWlXZC9CblM4VUZtQmtJMWNNaEZzSElnUVI5CkNJMTFEcWkwMlJhTzNQZGcwL1REZXgvNHVNYnJKa1p4eDh5SytEU1BPMmdCY0w4dGZITExIdE9rdjQwNUk0eFkKekNhaWdwNmZReXpUZC9heGZzbGlYVzA9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
type: kubernetes.io/tls
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: benchmark-ingress-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*.k8s.com"
    tls:
      mode: SIMPLE
      credentialName: gateway-credential
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: benchmark-virtual-service
spec:
  hosts:
  - "benchmark.k8s.com"
  gateways:
  - benchmark-ingress-gateway
  http:
    - match:
      - uri:
          prefix: "/"
      route:
      - destination:
          host: "echoserver.benchmark.svc.cluster.local"
          port:
            number: 80